# Generated by Django 4.1 on 2022-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_author_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Logo.jpg', null=True, upload_to='images/'),
        ),
    ]
